### ISSUE TITLE
aioss方式启动的时候，好像启动不起来？

### ISSUE THREAD

**Issue by yscxyjd** [Ehco1996/aioshadowsocks#124]
启动就这个问题，我其实不太了解python，只是简单的了解，这个如何解决？

D:\Desktop\新建文件夹 (2)\aioshadowsocks>aioss run_ss_server
[INFO]2021-01-16 22:30:04,173 _init_memory_db line:81 正在创建<Model: User>内存数据库
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\aioss.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\shadowsocks\__main__.py", line 7, in main
    fire.Fire(App)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\shadowsocks\app.py", line 144, in run_ss_server
    self._prepare()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\shadowsocks\app.py", line 97, in _prepare
    self.loop.add_signal_handler(signal.SIGTERM, self._shutdown)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 536, in add_signal_handler
    raise NotImplementedError
NotImplementedError

**Comment by PuckTeam** [comment]
![image](https://user-images.githubusercontent.com/49980280/104814865-0041c080-584c-11eb-9041-b5d48e47b5fb.png)

**Comment by Ehco1996** [comment]
@PuckTeam 

目前在windows下不能跑
可以去wsl下跑
