### ISSUE TITLE
直接python运行是运行app.py吗

### ISSUE THREAD

**Issue by ThereChave** [Ehco1996/aioshadowsocks#149]
直接运行是运行app.py吗？pip安装不上，也启动不起来

**Comment by Ehco1996** [comment]
贴一下报错的log

直接运行：`python -m shadowsocks run_ss_server`

**Comment by ThereChave** [comment]
`[root@ip= aioshadowsocks]# python3 -m shadowsocks run_ss_server
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/aioshadowsocks/shadowsocks/__main__.py", line 3, in <module>
    from shadowsocks.app import App
  File "/root/aioshadowsocks/shadowsocks/app.py", line 14, in <module>
    from shadowsocks.mdb import BaseModel, models
  File "/root/aioshadowsocks/shadowsocks/mdb/models.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined`

**Comment by Ehco1996** [comment]
@ThereChave python版本需要3.8
